version: '3'

services:
  db:
    container_name: postgres-auth-tests
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=authentication
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql
